import warnings

warnings.warn(
    """The module 'your_module_name' is deprecated and will be removed
    in a future release. Please use 'new_module_name' instead.""",
    DeprecationWarning,
    stacklevel=2,
)

VARIABLES = {
    r"\alpha": {"name": "Aperture radius"},
    r"A": {"name": "Object area"},
    r"\text{A'}": {"name": "Image area"},
    r"\text{B'}": {"name": "Image plane blur criterion"},
    r"\text{BFD}": {"name": "Back focal distance"},
    r"c": {"name": "Speed of light"},
    r"C": {"name": "Curvature"},
    r"\text{CC}": {"name": "Center of curvature"},
    r"d": {"name": "Front principal plane shifts"},
    r"\text{d'}": {"name": "Rear principal plane shifts"},
    r"D": {"name": "Diopters"},
    r"D_{airy}": {"name": "Airy disk diameter"},
    r"\text{DOF}": {"name": "Depth of focus, geometrical"},
    r"\text{Ir}": {"name": "Irradiance and illuminance"},
    r"\text{ee}_v": {"name": "Irradiance and illuminance"},
    r"\text{EFL}": {"name": "Effective focal length"},
    r"\text{eP}": {"name": "Entrance pupil"},
    r"\text{eR}": {"name": "Eye relief"},
    r"f": {"name": "Focal length"},
    r"f_{ee}": {"name": "Effective focal length"},
    r"f_F": {"name": "Front focal length"},
    r"f_R": {"name": "Rear focal length"},
    r"\text{f/hash}": {"name": "F-number"},
    r"\text{f/hash_w}": {"name": "Working F-number"},
    r"\delta_f": {"name": "Longitudinal chromatic aberration"},
    r"F": {"name": "Front focal point"},
    r"\text{F'}": {"name": "Rear focal point"},
    r"\text{FFD}": {"name": "Front focal distance"},
    r"\text{FFOV}": {"name": "Full field of view"},
    r"\text{FOB}": {"name": "Fractional object"},
    r"text{FOV}": {"name": "Field of view"},
    r"h": {"name": "Object height"},
    r"\text{h'}": {"name": "Image height"},
    r"H": {"name": "Lagrange invariant"},
    r"H_v": {"name": "Normalized field height"},
    r"H_{norm}": {"name": "Normalized field height"},
    r"\text{\text{e}xposure}": {"name": "Exposure"},
    r"\text{HFOV}": {"name": "Half field of view"},
    r"I": {"name": "Optical invariant"},
    r"I_v": {"name": "Intensity and luminous intensity"},
    r"L": {"name": "Object-to-image distance"},
    r"L_v": {"name": "Radiance and luminance"},
    r"L_H": {"name": "Hyperfocal distance"},
    r"L_{NEAR}": {"name": "Depth of field limits"},
    r"L_{FAR}": {"name": "Depth of field limits"},
    r"\text{LA}": {"name": "Longitudinal aberration"},
    r"m": {"name": "Transverse or lateral magnification"},
    r"\bar{m}": {"name": "Longitudinal magnification"},
    r"m_v": {"name": "Visual magnification (microscope)"},
    r"M": {"name": "Exitance"},
    r"M_v": {"name": "Luminous exitance"},
    r"\text{MP}": {
        "name": "Magnifying power (magnifier or telescope)",
    },
    r"\text{MTF}": {"name": "Modulation transfer function"},
    r"n": {"name": "Index of refraction"},
    r"N": {"name": "Front nodal point"},
    r"\text{N'}": {"name": "Rear nodal point"},
    r"\text{NA}": {"name": "Numerical aperture"},
    r"\text{OPL}": {"name": "Optical path length"},
    r"\text{OTL}": {"name": "Optical tube length"},
    r"P": {"name": "Partial dispersion ratio"},
    r"\text{P'}": {"name": "Front and rear principal points"},
    r"\text{PSF}": {"name": "Point spread function"},
    r"Q": {"name": "Energy"},
    r"r_P": {"name": "Pupil radius"},
    r"R": {"name": "Radius of curvature"},
    r"s": {"name": "Surface sag or a separation"},
    r"s_{prime}": {"name": "Object and image vertex distances"},
    r"S": {"name": "Seidel aberration coefficient"},
    r"\text{SR}": {"name": "Strehl ratio"},
    r"t": {"name": "Thickness"},
    r"T": {"name": "Temperature"},
    r"\text{TA}": {"name": "Transverse aberration"},
    r"\text{TA}_{CH}": {
        "name": "Transverse axial chromatic aberration",
    },
    r"\text{TIR}": {"name": "Total internal reflection"},
    r"\Delta_t": {"name": "Exposure time"},
    r"u": {"name": "Paraxial angles; marginal rays"},
    r"\bar{u}": {"name": "Chief rays"},
    r"U": {"name": "Real marginal ray angle"},
    r"V": {"name": "Abbe number"},
    r"\text{V'}": {"name": "Surface vertices"},
    r"W": {"name": "Wavefront error"},
    r"W_{IJK}": {"name": "Wavefront aberration coefficient"},
    r"\text{WD}": {"name": "Working distance"},
    r"X": {"name": "Object coordinates"},
    r"Y": {"name": "Object coordinates"},
    r"\text{X'}": {"name": "Image coordinates"},
    r"\text{Y'}": {"name": "Image coordinates"},
    r"x_p": {"name": "Normalized pupil coordinates"},
    r"x_P": {"name": "Normalized pupil coordinates"},
    r"\text{XP}": {"name": "Exit pupil"},
    r"y": {"name": "Paraxial ray heights; marginal rays"},
    r"\bar{y}": {"name": "Paraxial ray heights; chief rays"},
    r"z": {"name": "Optical axis"},
    r"\text{z'}": {"name": "Object and image distances"},
    r"\delta_z": {"name": "Image plane shift"},
    r"\delta_{\hat{z}}": {"name": "Depth of focus, diffraction"},
    r"\Delta_z": {"name": "Object and image separations"},
    r"\delta": {"name": "Prism deviation"},
    r"\delta_{MIN}": {"name": "Angle of minimum deviation"},
    r"\delta_{phi}": {
        "name": "Longitudinal chromatic aberration",
    },
    r"\Delta": {"name": "Prism dispersion"},
    r"\epsilon": {"name": "Prism secondary dispersion"},
    r"\epsilon_X": {"name": "Transverse ray errors (X-axis)"},
    r"\epsilon_Y": {"name": "Transverse ray errors (Y-axis)"},
    r"\epsilon_Z": {"name": "Longitudinal ray error"},
    r"\theta": {
        "name": "Angle of incidence, refraction or reflection",
    },
    r"\theta_C": {"name": "Critical angle"},
    r"\theta_{1/2}": {"name": "Half field of view angle"},
    r"\kappa": {"name": "Conic constant"},
    r"\lambda": {"name": "Wavelength"},
    r"\nu": {"name": "Abbe number"},
    r"\rho": {"name": "Reflectance"},
    r"\rho_{norm}": {"name": "Normalized pupil radius"},
    r"\tau": {"name": "Reduced thickness"},
    r"\phi": {"name": "Optical power"},
    r"\Phi": {"name": "Radiant power"},
    r"\Phi_V": {"name": "Luminous power"},
    r"\omega": {"name": "Optical angles; marginal rays"},
    r"\bar{omega}": {"name": "Optical angles; chief rays"},
    r"\Omega": {"name": "Solid angle"},
    r"\Xi": {"name": "Lagrange invariant"},
    r"p_p": {"name": "Pixel size (panchromatic)"},
    r"p_{ms}": {"name": "Pixel size (multispectral)"},
    r"h_{alt}": {"name": "Altitude"},
    r"\nu_N": {"name": "Nyquist frequency"},
    r"\nu_c": {"name": "Cutoff frequency"},
    r"\text{GSD}_p": {
        "name": "Ground sampling distance (panchromatic)",
    },
    r"\text{GSD}_{ms}": {
        "name": "Ground sampling distance (multispectral)",
    },
    r"\text{GSS}": {"name": "Ground spot size"},
    r"Q_{img}": {"name": "Imaging Q factor"},
    r"\text{Swath}": {"name": "Swath width"},
    r"r_p": {"name": "Resolution (panchromatic)"},
    r"r_{ms}": {"name": "Resolution (multispectral)"},
    r"M_d": {"name": "Mirror aperture"},
    r"f^{\prime}_R": {"name": "Rear focal length"},
}
